- name: get database dump
  s3:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    bucket: the-mast
    object: "/{{config_name}}-last-release/sql_backup-{{data_env}}.bz2"
    mode: get
    region: eu-west-1
    dest: /tmp/datadump.sql.bz2

- name: unzip the datadump
  shell: bzip2 -d /tmp/datadump.sql.bz2

- name: get uploads
  s3:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    bucket: the-mast
    object: "/{{config_name}}-last-release/site_uploads_backup-{{data_env}}.tar.bz2"
    mode: get
    region: eu-west-1
    dest: /tmp/uploads.tar.bz2

- name: import the data
  shell: mysql -D {{wordpress_installs[0].dbname}} </tmp/datadump.sql

- name: clean dump files
  file:
    state: absent
    path: "/tmp/datadump.sql"
